# Generated by Django 5.2.6 on 2025-12-04 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adocato", "0006_adotante_data_nascimento"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="raca",
            options={
                "ordering": ["nome"],
                "permissions": [
                    ("can_cadastrar_racas", "Pode gerenciar raças de gatos"),
                    ("can_excluir_racas", "Pode excluir raças de gatos"),
                ],
                "verbose_name": "Raça",
                "verbose_name_plural": "Raças",
            },
        ),
    ]
